### ISSUE TITLE
Errors if there is a directory that ends in .js like ipaddr.js

### ISSUE THREAD

**Issue by Sinjhin** [bit-docs/bit-docs#7]
```
{ Error: EISDIR: illegal operation on a directory, read
    at Error (native) errno: -21, code: 'EISDIR', syscall: 'read' }
/Users/sinjhin/Workspace/canjs/node_modules/bit-docs/lib/process/process.js:88
                processFile(filePath, data.toString(), docMap, siteConfig);
                                          ^

TypeError: Cannot read property 'toString' of undefined
    at /Users/sinjhin/Workspace/canjs/node_modules/bit-docs/lib/process/process.js:88:31
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:430:12)
```

**Comment by leoj3n** [comment]
I mean, I've never named a directory like that, but probably all that's needed is an `isDir()` kind of check when whatever parser is erring encounters `.js`.

**Comment by Sinjhin** [comment]
This was actually closed by:
https://github.com/bit-docs/bit-docs-glob-finder/pull/1

https://github.com/bit-docs/bit-docs/issues/8 is still a valid issue though.
